routes/web.php
<?php

use App\Http\Controllers\Admin\AffiliationManagementController;
use App\Http\Controllers\Admin\ApiMessagesController;
use App\Http\Controllers\Admin\BlockController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\FeedbackController;
use App\Http\Controllers\Admin\OwnerUserController;
use App\Http\Controllers\Admin\NotificationManagerController;
use App\Http\Controllers\Admin\PushNotificationController;
use App\Http\Controllers\Admin\ReportedUsersController;
use App\Http\Controllers\ReferralController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\JobApplicationController;
use App\Http\Controllers\Admin\RaffleController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TwilioSMSController;
use Kreait\Firebase\Contract\Firestore;
use Google\Cloud\Firestore\FirestoreClient;
use Google\Cloud\Core\Timestamp;
use Kreait\Firebase\ServiceAccount;
use Kreait\Firebase\Database;
use Google\Cloud\Firestore\FieldValue;
use Google\Cloud\Storage\StorageClient;
use Kreait\Firebase\Auth;

use App\Models\Admin\PushNotification;
use App\Models\Item;
use Doctrine\DBAL\Schema\Index;
use App\Jobs\changeIteamStatusFirebase;
use App\Models\Owner;
use Kreait\Firebase\Firestore as FirebaseFirestore;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// \Auth::routes(['register' => false]);

Route::get('/', function () {
    return view('commingsoon');
})->name('frontend.home');

Route::get('/success', function () {
    return view('sucess');
});

Route::get('/tandc', function () {
    return view('tc');
});

Route::get('/privacy', function () {
    return view('privacy');
});

Route::get('/emailView', function () {
    return view('email.welcomeMail');
});

Route::get('/deleteAuth/{email}', function ($email) {
    return updateFirebaseUserDeletedAtDocument($email);
    return view('privacy');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/send',[TwilioSMSController::class,'index']);

Route::get('/viewMailtem',function(){
    $item=Item::find(3);
    dispatch(new changeIteamStatusFirebase(1,"hide"));
    //new changeIteamStatusFirebase();
    //AddFirebaseItemDocument($item);
    // updateFirebaseItemDocument($item);
    // firebaseBlock("YjCg1iCedUaLmaZkFxWepzPg3Xl2","1");

    return "update";
    // $firestore = new Firestore([
    //     'keyFile' => json_decode(file_get_contents(__DIR__.'/../FirebaseKey.json'), true)
    //     ]);
    //     $updateData =  $firestore->collection('users')->document($uid);

    $data = [
        'name' => 'Los Angeles',
        'state' => 'CA',
        'country' => 'USA'
    ];
        $firestore = new FirestoreClient([
		'keyFile' => json_decode(file_get_contents(__DIR__.'/../FirebaseKey-dev.json'), true)
    	]);
    	try {

			$firestore->collection('users')->document("user")->set($data);

    	} catch (Exception $e) {
    		return array("status" => 401, "firebaseError" => $e->getMessage());
    	}

        dd($firestore);
//$factory = (new Factory)->withServiceAccount(__DIR__.'/../FirebaseKey.json');
    $factory->createFirestore();
    $studen= $factory->database()->collection('students')->newDocument();
    $studen->set([
        "fname"=>"jasmin",
        "lname" => "shukla",
        "age" => 24
    ]);
    dd("data Added");
    $auth = $factory->createAuth();
    $firestore = new Firestore();
    $database = $firestore->database();
    $database->getReference('config/website')
    ->set([
        'name' => 'My Application',
        'emails' => [
            'support' => 'support@domain.tld',
            'sales' => 'sales@domain.tld',
        ],
        'website' => 'https://app.domain.tld',
       ]);
    try {
        $user = $auth->getUserByEmail("jasmin@gmail.com");
        dd($user);
    } catch(Exception $e) {
        return array("status" => 401, "firebaseError" => $e->getMessage());
    }
dd($factory);

    
});

Route::get('/updatefirebase',function(){
    updateFirebaseUserDocument();
    echo "update";
    die();
});



Route::group(['namespace' => 'App\Http\Controllers'], function()
    {
		//Auth::routes();
		/* Start Custom Auth URL's */
			// Authentication Routes..
			Route::post('logout', 'Auth\LoginController@logout')->name('logout');
			// Registration Routes...
			Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
			Route::post('register', 'Auth\RegisterController@register');
			// Password Reset Routes...
			Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
			Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
			Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
			Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
			// Email Verification Routes...
			Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
			Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
			Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
			// Admin Urls
			Route::get('admin/login', 'Adminauth\LoginController@showLoginForm')->name('adminLoginFrom');
			Route::post('admin/login', 'Adminauth\LoginController@adminLogin')->name('adminlogin');
			Route::post('admin/logout', 'Adminauth\LoginController@logout')->name('adminlogout');
			Route::get('/admin/password/reset','Adminauth\ForgotPasswordController@showForgotPasswordForm')->name('forgotpasswordform');
			Route::post('/admin/password/email','Adminauth\ForgotPasswordController@sendResetLinkEmail')->name('adminforgotpassword');
			Route::get('/admin/password/reset/{token}','Adminauth\ResetPasswordController@showResetPasswordForm')->name('showResetPasswordForm');
			Route::post('/admin/password/reset','Adminauth\ResetPasswordController@reset')->name('adminResetPassword');
			/* END Custom Auth URL's */

            
    });
    
	Route::group([ 'namespace' => 'App\Http\Controllers\Admin','middleware' => ['auth:admin']], function()
	{
		/*DASHBOARD CONTROLLER*/
		Route::get('/','DashboardController@index');
		Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
        Route::post('dashboard', 'DashboardController@filter')->name('filter');
		Route::resource('user-profile', 'ProfileController');
        Route::post('/changePassword/{id}','ProfileController@changePassword')->name('changePassword');
        /*NOTIFICATION MESSAGE CONTROLLER*/
        Route::get('notification-messages/getAllData', 'NotificationMessageController@getAllData');
        Route::resource('notification-messages', 'NotificationMessageController');
        Route::get('notification-messages/getAllData', 'NotificationMessageController@getAllData');
        Route::resource('notification-messages', 'NotificationMessageController');
        Route::resource('Notification', 'PushNotificationController');

        /*REGISTERED USER CONTROLLER*/
        Route::resource('users', 'UsersController');
        //Route::resource('users', 'UsersController');
        Route::get('exportUsers', 'UsersController@exportUser');
        Route::get('block-users', [BlockController::class,'index']);
        Route::get('reported-users', [ReportedUsersController::class,'index'])->name('reported-users.index');
        Route::get('referral-users', [ReferralController::class,'index'])->name('referral-users.index');
        Route::resource('raffle-users', 'RaffleController');
        //Route::get('raffle-users', [RaffleController::class,'index'])->name('raffle-users.index');
        Route::post('reported-users/{user}/suspend/{action}', [ReportedUsersController::class,'suspend'])->name('reported-users.suspend');
        Route::post('reported-users/{user}/block', [ReportedUsersController::class,'block'])->name('reported-users.block');
        Route::delete('reported-users/{user}', [ReportedUsersController::class,'destroy'])->name('reported-users.destroy');
        Route::get('reported-users/exportUsers', 'ReportedUsersController@exportUser');

        Route::resource('Feedback', 'FeedbackController');
        Route::resource('Notification', 'PushNotificationController');
        Route::get('ApiMessages',[ApiMessagesController::class,'index'])->name('ApiMessages');
        Route::get('ApiMessages/{key}',[ApiMessagesController::class,'show'])->name('ApiMessages.show');
        Route::put('ApiMessages/{key}',[ApiMessagesController::class,'update'])->name('ApiMessages.update');
        Route::get('Affiliate', 'AffiliationManagementController@index')->name('Affiliate.index');
        Route::post('Affiliate/New', 'AffiliationManagementController@store')->name('createAffiliate');
        Route::delete('Affiliate/{affiliate}/delete', 'AffiliationManagementController@destroy')->name('deleteAffiliate');
        Route::post('Affiliate/{affiliate}/update', 'AffiliationManagementController@update')->name('updateAffiliate');
        Route::get('Affiliate/{affiliate}', 'AffiliationManagementController@show')->name('showAffiliate');

        
        Route::post('faq/sortable', 'FaqController@sortable');
        Route::resource('faq-management', 'FaqController');
        Route::resource('job-application', 'JobApplicationController',['names'=>'job-application']);


        Route::get('user-feedbacks/getalldata', 'FeedbackController@getalldata');

resources/views/admin/layouts/includes/footer.blade.php
<footer class="site-footer">
    <div class="site-footer-legal">© {{date("Y")}} {{config::get('constant.APP_NAME')}}</div>
  </footer>

<div class="modal fade in" id="logoutPopup" role="dialog" aria-hidden="false">
  <div class="modal-dialog modal-sm modal-sm-new">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Logout</h4>
        {{-- <button type="button" class="close" data-dismiss="modal">×</button> --}}
      </div>
      <form id="logout-form" action="{{ route('adminlogout') }}" method="POST">
          {{ csrf_field() }}
        <div class="modal-body text-center">
          <p class="delete-conform-p">Are you sure want to logout?</p>
        </div>


        <div class="modal-footer">
          <button type="submit" class="btn btn-primary waves-effect waves-classic" >Yes</button>
          <button type="button" class="btn btn-danger waves-effect waves-classic" data-dismiss="modal">Close</button>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- End changes -->
<div class="modal fade" id="dataInfoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel3" aria-hidden="true"></div>

<!-- BOC image crop pop-up -->
<div id="insertimageModal" class="modal" role="dialog">
 <div class="modal-dialog modal-lg">
  <div class="modal-content">
      <div class="modal-header slidePanel-header bg-light-green-600">
        <div class="overlay-top overlay-panel overlay-background bg-light-green-600 rotate-color-combo">
          <div class="slidePanel-actions btn-group btn-group-flat" aria-label="actions" role="group">
            <button type="button" class="btn btn-pure slidePanel-close icon md-close btnClosePopup2" data-dismiss="modal" aria-hidden="true" aria-label="Close"></button>
          </div>
          <h5 class="stage-name taskboard-stage-title">Crop Image</h5>
        </div>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12 text-center">
            <div id="image_demo" class="imageCropPreview" ></div>
          </div>
        </div>
        <div class="row remove-wrap" >
          <div class="col-md-6 text-left">
            <button type="button" class="btn btn-secondary crop-btn btnClosePopup2" id="btnClosePopup2" data-dismiss="modal" >Close</button>
          </div>
          <div class="col-md-6 text-right">
            <button class="btn btn-primary crop_image crop-btn" id="">Crop Image</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- EOC  image crop pop-up -->

  <!-- Core  -->
  <script src="{{ asset('themes/admin/assets/global/vendor/babel-external-helpers/babel-external-helpersfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/jquery/jquery.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/popper-js/umd/popper.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/bootstrap/bootstrap.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/animsition/animsition.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/mousewheel/jquery.mousewheel.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/asscrollbar/jquery-asScrollbar.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/asscrollable/jquery-asScrollable.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/ashoverscroll/jquery-asHoverScroll.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/js/Component.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/js/Plugin.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/js/Base.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/js/Config.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/js/Section/Menubar.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/js/Section/Sidebar.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/js/Section/PageAside.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/js/Plugin/menu.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/js/Site.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/toastr/toastr.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/examples/js/dashboard/v1.minfd53.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/js/loadingoverlay.min.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/datatables.net/jquery.dataTablesfd53.js?v4.0.1') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/datatables.net-bs4/dataTables.bootstrap4fd53.js?v4.0.1') }}"></script>

  <script src="{{asset('themes/admin/assets/js/croppie.2.6.4.js')}}"></script>
  <script src="{{ asset('themes/admin/assets/js/jquery.validate.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/js/form-validation.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/js/modal.js') }}"></script>

  <script src="{{ asset('themes/admin/assets/global/vendor/bootstrap-datepicker/bootstrap-datepicker.minfd53.js?v4.0.1') }}"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>


<script type="text/javascript">
$(function() {
    $(document).ready(function(){
      $.ajaxSetup({
          headers: {
            'X-CSRF-Token': $('meta[name="_token"]').attr('content')
          }
      });
    });
    toastr.options = {
      "closeButton": true,
      "debug": false,
      "newestOnTop": false,
      "progressBar": true,
      "positionClass": "toast-top-center",
      "preventDuplicates": false,
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }
  <?php
    $messageArr = ['warning', 'danger', 'info', 'error', 'success'];
    foreach($messageArr as $message)
    {
      if(session()->has($message))
      {
    ?>
      $(function () {
          toastr["{{$message}}"]("{{session()->get($message)}}");
      });
    <?php
      }
    }
    ?>
});
function logout()
{
    Swal.fire({
        icon: 'warning',
        title:'Rotate',
        html: "Are you sure you want to logout?",
        showCancelButton: true,
        confirmButtonText: 'Yes',
        confirmButtonColor: '#ff0000',
        cancelButtonText: 'No',
        cancelButtonColor: '#808080',
        }).then((result) => {
        if (result.isConfirmed) {
            $.LoadingOverlay("show", {
              image: "/themes/loader.gif",
            });
            $.ajax({
                type : "POST",
                url : "{{ route('adminlogout') }}",
                dataType: 'html',
                headers: {
                    'X-CSRF-TOKEN': '<?= csrf_token() ?>'
                },
                success : function(response) {
                    $.LoadingOverlay("hide");
                    location.reload();
                }
            });
        }
    })
}

</script>

resources/views/admin/layouts/includes/header.blade.php
<nav class="site-navbar navbar navbar-default navbar-inverse navbar-fixed-top navbar-mega"
    role="navigation">

    <div class="navbar-header">
      <button type="button" class="navbar-toggler hamburger hamburger-close navbar-toggler-left hided"
        data-toggle="menubar">
        <span class="sr-only">Toggle navigation</span>
        <span class="hamburger-bar"></span>
      </button>
      <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-collapse"
        data-toggle="collapse">
        <i class="icon md-more" aria-hidden="true"></i>
      </button>
      <div class="navbar-brand navbar-brand-center">
         <img class="navbar-brand-logo" src="{{url(Config::get('constant.ADMIN.HEADER_LOGO'))}}" >
        {{-- <span class="navbar-brand-text hidden-xs-down"> Remark</span> --}}
      </div>
      {{-- <button type="button" class="navbar-toggler collapsed" data-target="#site-navbar-search"
        data-toggle="collapse">
        <span class="sr-only">Toggle Search</span>
        <i class="icon md-search" aria-hidden="true"></i>
      </button> --}}
    </div>

    <div class="navbar-container container-fluid">
      <!-- Navbar Collapse -->
      <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
        <!-- Navbar Toolbar -->
        <ul class="nav navbar-toolbar">
          <li class="nav-item hidden-float" id="toggleMenubar">
            <a class="nav-link" data-toggle="menubar" href="#" role="button">
                <i class="icon hamburger hamburger-arrow-left">
                  <span class="sr-only">Toggle menubar</span>
                  <span class="hamburger-bar"></span>
                </i>
              </a>
          </li>
          {{-- <li class="nav-item hidden-sm-down" id="toggleFullscreen">
            <a class="nav-link icon icon-fullscreen" data-toggle="fullscreen" href="#" role="button">
<!--               <span class="sr-only">Toggle fullscreen</span>
 -->            </a>
          </li> --}}
        </ul>
        <!-- End Navbar Toolbar -->

        <!-- Navbar Toolbar Right -->
        <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">

          <li class="nav-item dropdown">
            <a class="nav-link navbar-avatar" data-toggle="dropdown" href="#" aria-expanded="false"
              data-animation="scale-up" role="button">
              <span class="avatar avatar-online">
                <img src="{{!empty(Auth::guard('admin')->user()->profile_pics) ? url('uploads/profile_pics/'.Auth::guard('admin')->user()->profile_pics) : asset('themes/admin/assets/global/portraits/5.jpg') }}" alt="{{Auth::guard('admin')->user()->name}}">
                <i></i>
              </span>
              <label class="author-name">{{Auth::guard('admin')->user()->name}}</label>
            </a>
            <div class="dropdown-menu" role="menu">
              <a class="dropdown-item" href="{{route('user-profile.index')}}" role="menuitem"><i class="icon md-account" aria-hidden="true"></i> Profile</a>
              <a class="dropdown-item" href="javascript:void(0)" onclick="logout()" role="menuitem"><i class="icon md-power" aria-hidden="true"></i> Logout</a>
            </div>
          </li>
        </ul>
        <!-- End Navbar Toolbar Right -->
      </div>
      <!-- End Navbar Collapse -->

    </div>
  </nav>

resources/views/admin/layouts/includes/modalError.blade.php
{{-- {{ Html::style('admin_theme/assets/css/custom.css') }} --}}
<div class="modal-dialog" id="myinformationModal">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">Opps!!</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
<div class="modal-body" id="informationModelBody"> 
    <div class="row">
        <div class="col-md-12 text-danger text-center">
            <div class="form-group">
                <i class="fa fa-exclamation-triangle fa-5x" aria-hidden="true"></i>
                <h5>Opps!! Something went wrong. Please try again.11</h5>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-danger text-center">
            <div class="form-group">
                <button type="button" class="btn btn-danger btn-flat" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</div>
</div> 

resources/views/admin/layouts/includes/sidebar.blade.php
<div class="site-menubar site-menubar-light">
    <div class="site-menubar-body">
      <div>
        <div>
          <ul class="site-menu" data-plugin="menu">
            <li class="site-menu-item @if(in_array('dashboard', Request::segments())) active @endif">
              <a href="{{route('admin.dashboard')}}">
                <i class="site-menu-icon md-view-dashboard" aria-hidden="true"></i>
                <span class="site-menu-title">{{ __('admin.dashboard-menu') }}</span>
              </a>
            </li>
            

            <li class="site-menu-item @if(in_array('users', Request::segments())) active @endif">
              <a href="{{route('users.index')}}">
                <i class="site-menu-icon md-accounts-list" aria-hidden="true"></i>
                <span class="site-menu-title">{{ __('admin.users-menu') }}</span>
              </a>
            </li>
            <li class="site-menu-item @if(in_array('referral-users', Request::segments())) active @endif">
              <a href="{{route('referral-users.index')}}">
                <i class="site-menu-icon icon md-receipt"></i>
                <span class="site-menu-title">{{ __('admin.referral-menu') }}</span>
              </a>
            </li>
            <li class="site-menu-item @if(in_array('raffle-users', Request::segments())) active @endif">
              <a href="{{route('raffle-users.index')}}">
                <i class="site-menu-icon icon md-receipt"></i>
                <span class="site-menu-title">{{ __('admin.raffle-menu') }}</span>
              </a>
            </li>
            <li class="site-menu-item has-sub @if(in_array('brands', Request::segments())) active @endif">
              <a href="javascript:void(0)">
                <i class="site-menu-icon md-present-to-all" aria-hidden="true"></i>
                <span class="site-menu-title">{{ __('admin.brand-menu') }}</span>
              </a>
              <ul class="site-menu-sub">
                <li class="site-menu-item @if(in_array('request', Request::segments())) active @endif">
                  <a href="{{route('brand.List',["status"=>"request"])}}">
                    <span class="site-menu-title">Request</span>
                  </a>
                </li>
                <li class="site-menu-item @if(in_array('Approved', Request::segments())) active @endif">
                  <a href="{{route('brand.List',["status"=>"Approved"])}}">
                    <span class="site-menu-title">Approved</span>
                  </a>
                </li>
                <li class="site-menu-item @if(in_array('Rejected', Request::segments())) active @endif">
                  <a href="{{route('brand.List',["status"=>"Rejected"])}}">
                    <span class="site-menu-title">Rejected</span>
                  </a>
                </li>
              </ul> 
            </li>

            <li class="site-menu-item @if(in_array('reported-users', Request::segments())) active @endif">
              <a href="{{route('reported-users.index')}}">
                <i class="site-menu-icon md-accounts-list" aria-hidden="true"></i>
                <span class="site-menu-title">{{ __('admin.users-reported-menu') }}</span>
              </a>
            </li>
            <li class="site-menu-item @if(in_array('job-application', Request::segments())) active @endif">
              <a href="{{route('job-application.index')}}">
                <i class="site-menu-icon md-receipt" aria-hidden="true"></i>
                <span class="site-menu-title">{{ __('admin.job-application-menu') }}</span>
              </a>
            </li>
            <li class="site-menu-item @if(in_array('Notification', Request::segments())) active @endif">
              <a href="{{url('Notification')}}">
                <i class="site-menu-icon icon md-notifications"></i>
                <span class="site-menu-title">{{ __('admin.notification-menu') }}</span>
              </a>
            </li>

            <li class="site-menu-item @if(in_array('Affiliate', Request::segments())) active @endif">
              <a href="{{route('Affiliate.index')}}">
                <i class="site-menu-icon md-library" aria-hidden="true"></i>
                <span class="site-menu-title">{{ __('admin.Affiliate-menu') }}</span>
              </a>
            </li>
            
            <li class="site-menu-item @if(in_array('Feedback', Request::segments())) active @endif">
              <a href="{{route('Feedback.index')}}">
                <i class="site-menu-icon md-comment-list" aria-hidden="true"></i>
                <span class="site-menu-title">{{ __('admin.feedback-menu') }}</span>
              </a>
            </li>
            <li class="site-menu-item @if(in_array('faq-management', Request::segments())) active @endif">
              <a href="{{route('faq-management.index')}}">
                <i class="site-menu-icon md-receipt" aria-hidden="true"></i>
                <span class="site-menu-title">{{ __('admin.faq-menu') }}</span>
              </a>
            </li>

       

            {{-- <li class="site-menu-item @if(in_array('Notification', Request::segments())) active @endif">
              <a href="{{url('admin/Notification')}}">
                <i class="site-menu-icon icon md-notifications"></i>
                <span class="site-menu-title">{{ __('admin.notification-menu') }}</span>
              </a>
            </li>
             --}}


              
              <li class="site-menu-item @if(in_array('ApiMessages', Request::segments())) active @endif">
                <a href="{{url('ApiMessages')}}">
                  <i class="site-menu-icon icon md-receipt"></i>
                  <span class="site-menu-title">{{ __('admin.api-messages-menu') }}</span>
                </a>
              </li>

          </ul>
        </div>
      </div>
    </div>
  </div>